/* FluffyFlight data: continents + real major airports.
   Kept in its own file so the airport list is easy to extend. */

// Continents: centroid (for routing land clicks) + bounding box (for zoom).
const CONTINENTS = {
  "North America": { center: [40, -100], bounds: [[7, -168], [72, -52]] },
  "South America": { center: [-15, -60], bounds: [[-56, -82], [13, -34]] },
  "Europe":        { center: [50, 10],   bounds: [[34, -25], [71, 45]] },
  "Africa":        { center: [3, 20],    bounds: [[-35, -18], [37, 52]] },
  "Asia":          { center: [45, 90],   bounds: [[5, 40], [75, 150]] },
  "Oceania":       { center: [-25, 140], bounds: [[-48, 110], [-5, 179]] },
};

// Real major international airports (name, IATA, city, country, lat, lon).
const AIRPORTS = [
  // North America
  { iata:"JFK", name:"John F. Kennedy Intl", city:"New York",      country:"USA",     cont:"North America", lat:40.6413, lon:-73.7781 },
  { iata:"LAX", name:"Los Angeles Intl",     city:"Los Angeles",   country:"USA",     cont:"North America", lat:33.9416, lon:-118.4085 },
  { iata:"ORD", name:"O'Hare Intl",          city:"Chicago",       country:"USA",     cont:"North America", lat:41.9742, lon:-87.9073 },
  { iata:"ATL", name:"Hartsfield–Jackson",   city:"Atlanta",       country:"USA",     cont:"North America", lat:33.6407, lon:-84.4277 },
  { iata:"DFW", name:"Dallas/Fort Worth",    city:"Dallas",        country:"USA",     cont:"North America", lat:32.8998, lon:-97.0403 },
  { iata:"DEN", name:"Denver Intl",          city:"Denver",        country:"USA",     cont:"North America", lat:39.8561, lon:-104.6737 },
  { iata:"SFO", name:"San Francisco Intl",   city:"San Francisco", country:"USA",     cont:"North America", lat:37.6213, lon:-122.3790 },
  { iata:"SEA", name:"Seattle–Tacoma",       city:"Seattle",       country:"USA",     cont:"North America", lat:47.4502, lon:-122.3088 },
  { iata:"MIA", name:"Miami Intl",           city:"Miami",         country:"USA",     cont:"North America", lat:25.7959, lon:-80.2870 },
  { iata:"BOS", name:"Logan Intl",           city:"Boston",        country:"USA",     cont:"North America", lat:42.3656, lon:-71.0096 },
  { iata:"LAS", name:"Harry Reid Intl",      city:"Las Vegas",     country:"USA",     cont:"North America", lat:36.0840, lon:-115.1537 },
  { iata:"IAD", name:"Washington Dulles",    city:"Washington",    country:"USA",     cont:"North America", lat:38.9531, lon:-77.4565 },
  { iata:"YYZ", name:"Toronto Pearson",      city:"Toronto",       country:"Canada",  cont:"North America", lat:43.6777, lon:-79.6248 },
  { iata:"YVR", name:"Vancouver Intl",       city:"Vancouver",     country:"Canada",  cont:"North America", lat:49.1947, lon:-123.1792 },
  { iata:"YUL", name:"Montréal–Trudeau",     city:"Montréal",      country:"Canada",  cont:"North America", lat:45.4706, lon:-73.7408 },
  { iata:"MEX", name:"Mexico City Intl",     city:"Mexico City",   country:"Mexico",  cont:"North America", lat:19.4361, lon:-99.0719 },
  { iata:"CUN", name:"Cancún Intl",          city:"Cancún",        country:"Mexico",  cont:"North America", lat:21.0365, lon:-86.8771 },
  { iata:"PTY", name:"Tocumen Intl",         city:"Panama City",   country:"Panama",  cont:"North America", lat:9.0714,  lon:-79.3835 },

  // South America
  { iata:"GRU", name:"São Paulo/Guarulhos",   city:"São Paulo",     country:"Brazil",    cont:"South America", lat:-23.4356, lon:-46.4731 },
  { iata:"GIG", name:"Rio de Janeiro/Galeão", city:"Rio de Janeiro",country:"Brazil",    cont:"South America", lat:-22.8090, lon:-43.2506 },
  { iata:"BSB", name:"Brasília Intl",         city:"Brasília",      country:"Brazil",    cont:"South America", lat:-15.8697, lon:-47.9208 },
  { iata:"EZE", name:"Ministro Pistarini",    city:"Buenos Aires",  country:"Argentina", cont:"South America", lat:-34.8222, lon:-58.5358 },
  { iata:"SCL", name:"Arturo Merino Benítez", city:"Santiago",      country:"Chile",     cont:"South America", lat:-33.3930, lon:-70.7858 },
  { iata:"BOG", name:"El Dorado Intl",        city:"Bogotá",        country:"Colombia",  cont:"South America", lat:4.7016,   lon:-74.1469 },
  { iata:"LIM", name:"Jorge Chávez Intl",     city:"Lima",          country:"Peru",      cont:"South America", lat:-12.0219, lon:-77.1143 },
  { iata:"UIO", name:"Mariscal Sucre",        city:"Quito",         country:"Ecuador",   cont:"South America", lat:-0.1292,  lon:-78.3575 },
  { iata:"CCS", name:"Simón Bolívar Intl",    city:"Caracas",       country:"Venezuela", cont:"South America", lat:10.6013,  lon:-66.9911 },
  { iata:"MVD", name:"Carrasco Intl",         city:"Montevideo",    country:"Uruguay",   cont:"South America", lat:-34.8384, lon:-56.0308 },
  { iata:"ASU", name:"Silvio Pettirossi",     city:"Asunción",      country:"Paraguay",  cont:"South America", lat:-25.2399, lon:-57.5199 },
  { iata:"LPB", name:"El Alto Intl",          city:"La Paz",        country:"Bolivia",   cont:"South America", lat:-16.5133, lon:-68.1925 },

  // Europe
  { iata:"LHR", name:"Heathrow",              city:"London",     country:"UK",          cont:"Europe", lat:51.4700, lon:-0.4543 },
  { iata:"LGW", name:"Gatwick",               city:"London",     country:"UK",          cont:"Europe", lat:51.1537, lon:-0.1821 },
  { iata:"CDG", name:"Charles de Gaulle",     city:"Paris",      country:"France",      cont:"Europe", lat:49.0097, lon:2.5479 },
  { iata:"FRA", name:"Frankfurt",             city:"Frankfurt",  country:"Germany",     cont:"Europe", lat:50.0379, lon:8.5622 },
  { iata:"MUC", name:"Munich",                city:"Munich",     country:"Germany",     cont:"Europe", lat:48.3538, lon:11.7861 },
  { iata:"AMS", name:"Schiphol",              city:"Amsterdam",  country:"Netherlands", cont:"Europe", lat:52.3105, lon:4.7683 },
  { iata:"MAD", name:"Adolfo Suárez Barajas", city:"Madrid",     country:"Spain",       cont:"Europe", lat:40.4983, lon:-3.5676 },
  { iata:"BCN", name:"Barcelona–El Prat",     city:"Barcelona",  country:"Spain",       cont:"Europe", lat:41.2974, lon:2.0833 },
  { iata:"FCO", name:"Fiumicino",             city:"Rome",       country:"Italy",       cont:"Europe", lat:41.8003, lon:12.2389 },
  { iata:"ZRH", name:"Zürich",                city:"Zürich",     country:"Switzerland", cont:"Europe", lat:47.4582, lon:8.5555 },
  { iata:"VIE", name:"Vienna Intl",           city:"Vienna",     country:"Austria",     cont:"Europe", lat:48.1103, lon:16.5697 },
  { iata:"CPH", name:"Copenhagen",            city:"Copenhagen", country:"Denmark",     cont:"Europe", lat:55.6180, lon:12.6508 },
  { iata:"ARN", name:"Stockholm Arlanda",     city:"Stockholm",  country:"Sweden",      cont:"Europe", lat:59.6519, lon:17.9186 },
  { iata:"OSL", name:"Oslo Gardermoen",       city:"Oslo",       country:"Norway",      cont:"Europe", lat:60.1939, lon:11.1004 },
  { iata:"HEL", name:"Helsinki-Vantaa",       city:"Helsinki",   country:"Finland",     cont:"Europe", lat:60.3172, lon:24.9633 },
  { iata:"DUB", name:"Dublin",                city:"Dublin",     country:"Ireland",     cont:"Europe", lat:53.4264, lon:-6.2499 },
  { iata:"LIS", name:"Humberto Delgado",      city:"Lisbon",     country:"Portugal",    cont:"Europe", lat:38.7742, lon:-9.1342 },
  { iata:"ATH", name:"Eleftherios Venizelos", city:"Athens",     country:"Greece",      cont:"Europe", lat:37.9364, lon:23.9445 },
  { iata:"BRU", name:"Brussels",              city:"Brussels",   country:"Belgium",     cont:"Europe", lat:50.9010, lon:4.4844 },
  { iata:"WAW", name:"Warsaw Chopin",         city:"Warsaw",     country:"Poland",      cont:"Europe", lat:52.1657, lon:20.9671 },
  { iata:"PRG", name:"Václav Havel",          city:"Prague",     country:"Czechia",     cont:"Europe", lat:50.1008, lon:14.2600 },
  { iata:"IST", name:"Istanbul Airport",      city:"Istanbul",   country:"Turkey",      cont:"Europe", lat:41.2753, lon:28.7519 },
  { iata:"SVO", name:"Sheremetyevo",          city:"Moscow",     country:"Russia",      cont:"Europe", lat:55.9726, lon:37.4146 },

  // Africa
  { iata:"JNB", name:"O. R. Tambo Intl",    city:"Johannesburg",  country:"South Africa", cont:"Africa", lat:-26.1367, lon:28.2411 },
  { iata:"CPT", name:"Cape Town Intl",      city:"Cape Town",     country:"South Africa", cont:"Africa", lat:-33.9715, lon:18.6021 },
  { iata:"CAI", name:"Cairo Intl",          city:"Cairo",         country:"Egypt",        cont:"Africa", lat:30.1219,  lon:31.4056 },
  { iata:"LOS", name:"Murtala Muhammed",    city:"Lagos",         country:"Nigeria",      cont:"Africa", lat:6.5774,   lon:3.3212 },
  { iata:"ABV", name:"Nnamdi Azikiwe Intl", city:"Abuja",         country:"Nigeria",      cont:"Africa", lat:9.0068,   lon:7.2632 },
  { iata:"NBO", name:"Jomo Kenyatta Intl",  city:"Nairobi",       country:"Kenya",        cont:"Africa", lat:-1.3192,  lon:36.9278 },
  { iata:"CMN", name:"Mohammed V Intl",     city:"Casablanca",    country:"Morocco",      cont:"Africa", lat:33.3675,  lon:-7.5897 },
  { iata:"ADD", name:"Bole Intl",           city:"Addis Ababa",   country:"Ethiopia",     cont:"Africa", lat:8.9779,   lon:38.7993 },
  { iata:"ALG", name:"Houari Boumediene",   city:"Algiers",       country:"Algeria",      cont:"Africa", lat:36.6910,  lon:3.2154 },
  { iata:"TUN", name:"Tunis–Carthage",      city:"Tunis",         country:"Tunisia",      cont:"Africa", lat:36.8510,  lon:10.2272 },
  { iata:"ACC", name:"Kotoka Intl",         city:"Accra",         country:"Ghana",        cont:"Africa", lat:5.6052,   lon:-0.1668 },
  { iata:"DSS", name:"Blaise Diagne Intl",  city:"Dakar",         country:"Senegal",      cont:"Africa", lat:14.6700,  lon:-17.0732 },
  { iata:"DAR", name:"Julius Nyerere Intl", city:"Dar es Salaam", country:"Tanzania",     cont:"Africa", lat:-6.8781,  lon:39.2026 },
  { iata:"LAD", name:"Quatro de Fevereiro", city:"Luanda",        country:"Angola",       cont:"Africa", lat:-8.8584,  lon:13.2312 },
  { iata:"MRU", name:"Sir S. Ramgoolam",    city:"Port Louis",    country:"Mauritius",    cont:"Africa", lat:-20.4302, lon:57.6836 },

  // Asia
  { iata:"HND", name:"Tokyo Haneda",       city:"Tokyo",        country:"Japan",        cont:"Asia", lat:35.5494, lon:139.7798 },
  { iata:"NRT", name:"Tokyo Narita",       city:"Tokyo",        country:"Japan",        cont:"Asia", lat:35.7720, lon:140.3929 },
  { iata:"KIX", name:"Kansai Intl",        city:"Osaka",        country:"Japan",        cont:"Asia", lat:34.4347, lon:135.2440 },
  { iata:"ICN", name:"Incheon Intl",       city:"Seoul",        country:"South Korea",  cont:"Asia", lat:37.4602, lon:126.4407 },
  { iata:"PEK", name:"Beijing Capital",    city:"Beijing",      country:"China",        cont:"Asia", lat:40.0799, lon:116.6031 },
  { iata:"PVG", name:"Shanghai Pudong",    city:"Shanghai",     country:"China",        cont:"Asia", lat:31.1443, lon:121.8083 },
  { iata:"CAN", name:"Guangzhou Baiyun",   city:"Guangzhou",    country:"China",        cont:"Asia", lat:23.3924, lon:113.2988 },
  { iata:"CTU", name:"Chengdu Tianfu",     city:"Chengdu",      country:"China",        cont:"Asia", lat:30.3122, lon:104.4411 },
  { iata:"HKG", name:"Hong Kong Intl",     city:"Hong Kong",    country:"China",        cont:"Asia", lat:22.3080, lon:113.9185 },
  { iata:"TPE", name:"Taoyuan Intl",       city:"Taipei",       country:"Taiwan",       cont:"Asia", lat:25.0777, lon:121.2328 },
  { iata:"SIN", name:"Changi",             city:"Singapore",    country:"Singapore",    cont:"Asia", lat:1.3644,  lon:103.9915 },
  { iata:"KUL", name:"Kuala Lumpur Intl",  city:"Kuala Lumpur", country:"Malaysia",     cont:"Asia", lat:2.7456,  lon:101.7099 },
  { iata:"BKK", name:"Suvarnabhumi",       city:"Bangkok",      country:"Thailand",     cont:"Asia", lat:13.6900, lon:100.7501 },
  { iata:"CGK", name:"Soekarno–Hatta",     city:"Jakarta",      country:"Indonesia",    cont:"Asia", lat:-6.1256, lon:106.6559 },
  { iata:"MNL", name:"Ninoy Aquino Intl",  city:"Manila",       country:"Philippines",  cont:"Asia", lat:14.5086, lon:121.0197 },
  { iata:"HAN", name:"Noi Bai Intl",       city:"Hanoi",        country:"Vietnam",      cont:"Asia", lat:21.2212, lon:105.8072 },
  { iata:"SGN", name:"Tan Son Nhat",       city:"Ho Chi Minh",  country:"Vietnam",      cont:"Asia", lat:10.8188, lon:106.6519 },
  { iata:"DEL", name:"Indira Gandhi Intl", city:"Delhi",        country:"India",        cont:"Asia", lat:28.5562, lon:77.1000 },
  { iata:"BOM", name:"Chhatrapati Shivaji",city:"Mumbai",       country:"India",        cont:"Asia", lat:19.0896, lon:72.8656 },
  { iata:"BLR", name:"Kempegowda Intl",    city:"Bengaluru",    country:"India",        cont:"Asia", lat:13.1986, lon:77.7066 },
  { iata:"HYD", name:"Rajiv Gandhi Intl",  city:"Hyderabad",    country:"India",        cont:"Asia", lat:17.2403, lon:78.4294 },
  { iata:"CMB", name:"Bandaranaike Intl",  city:"Colombo",      country:"Sri Lanka",    cont:"Asia", lat:7.1808,  lon:79.8841 },
  { iata:"DAC", name:"Hazrat Shahjalal",   city:"Dhaka",        country:"Bangladesh",   cont:"Asia", lat:23.8513, lon:90.4086 },
  { iata:"KHI", name:"Jinnah Intl",        city:"Karachi",      country:"Pakistan",     cont:"Asia", lat:24.9065, lon:67.1608 },
  { iata:"DXB", name:"Dubai Intl",         city:"Dubai",        country:"UAE",          cont:"Asia", lat:25.2532, lon:55.3657 },
  { iata:"AUH", name:"Zayed Intl",         city:"Abu Dhabi",    country:"UAE",          cont:"Asia", lat:24.4330, lon:54.6511 },
  { iata:"DOH", name:"Hamad Intl",         city:"Doha",         country:"Qatar",        cont:"Asia", lat:25.2731, lon:51.6080 },
  { iata:"RUH", name:"King Khalid Intl",   city:"Riyadh",       country:"Saudi Arabia", cont:"Asia", lat:24.9576, lon:46.6988 },
  { iata:"JED", name:"King Abdulaziz Intl",city:"Jeddah",       country:"Saudi Arabia", cont:"Asia", lat:21.6796, lon:39.1565 },
  { iata:"TLV", name:"Ben Gurion",         city:"Tel Aviv",     country:"Israel",       cont:"Asia", lat:32.0114, lon:34.8867 },
  { iata:"ALA", name:"Almaty Intl",        city:"Almaty",       country:"Kazakhstan",   cont:"Asia", lat:43.3521, lon:77.0405 },
  { iata:"TAS", name:"Islam Karimov Intl", city:"Tashkent",     country:"Uzbekistan",   cont:"Asia", lat:41.2579, lon:69.2812 },

  // Oceania
  { iata:"SYD", name:"Kingsford Smith", city:"Sydney",       country:"Australia",   cont:"Oceania", lat:-33.9399, lon:151.1753 },
  { iata:"MEL", name:"Melbourne",       city:"Melbourne",    country:"Australia",   cont:"Oceania", lat:-37.6690, lon:144.8410 },
  { iata:"BNE", name:"Brisbane",        city:"Brisbane",     country:"Australia",   cont:"Oceania", lat:-27.3842, lon:153.1175 },
  { iata:"PER", name:"Perth",           city:"Perth",        country:"Australia",   cont:"Oceania", lat:-31.9385, lon:115.9672 },
  { iata:"ADL", name:"Adelaide",        city:"Adelaide",     country:"Australia",   cont:"Oceania", lat:-34.9450, lon:138.5306 },
  { iata:"CNS", name:"Cairns",          city:"Cairns",       country:"Australia",   cont:"Oceania", lat:-16.8858, lon:145.7553 },
  { iata:"OOL", name:"Gold Coast",      city:"Gold Coast",   country:"Australia",   cont:"Oceania", lat:-28.1644, lon:153.5050 },
  { iata:"AKL", name:"Auckland",        city:"Auckland",     country:"New Zealand", cont:"Oceania", lat:-37.0082, lon:174.7850 },
  { iata:"WLG", name:"Wellington",      city:"Wellington",   country:"New Zealand", cont:"Oceania", lat:-41.3272, lon:174.8053 },
  { iata:"CHC", name:"Christchurch",    city:"Christchurch", country:"New Zealand", cont:"Oceania", lat:-43.4894, lon:172.5322 },
  { iata:"NAN", name:"Nadi Intl",       city:"Nadi",         country:"Fiji",        cont:"Oceania", lat:-17.7554, lon:177.4434 },
  { iata:"POM", name:"Jacksons Intl",   city:"Port Moresby", country:"Papua New Guinea", cont:"Oceania", lat:-9.4438, lon:147.2200 },
  { iata:"PPT", name:"Faa'a Intl",      city:"Papeete",      country:"French Polynesia", cont:"Oceania", lat:-17.5537, lon:-149.6065 },
  { iata:"NOU", name:"La Tontouta",     city:"Nouméa",       country:"New Caledonia",    cont:"Oceania", lat:-22.0146, lon:166.2129 },
];
